#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kata-qemu-lite
Version  : 2.11.0
Release  : 10
URL      : https://github.com/kata-containers/qemu/archive/qemu-lite-2.11.0.tar.gz
Source0  : https://github.com/kata-containers/qemu/archive/qemu-lite-2.11.0.tar.gz
Source1  : https://github.com/qemu/capstone/archive/22ead3e0bfdb87516656453336160e0a37b066bf.tar.gz
Source2  : https://github.com/qemu/keycodemapdb/archive/10739aa26051a5d49d88132604539d3ed085e72e.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 LGPL-2.1 NCSA Python-2.0
Requires: kata-qemu-lite-bin = %{version}-%{release}
Requires: kata-qemu-lite-data = %{version}-%{release}
Requires: kata-qemu-lite-libexec = %{version}-%{release}
Requires: kata-qemu-lite-license = %{version}-%{release}
Requires: kata-qemu-lite-bin
Requires: kata-qemu-lite-data
BuildRequires : glib-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : pkgconfig(pixman-1)
BuildRequires : python-dev
BuildRequires : zlib-dev
Patch1: configure.patch
Patch2: memfd-fix-configure-test.patch
Patch3: CVE-2020-15863.patch

%description
===========
QEMU is a generic and open source machine & userspace emulator and
virtualizer.

%package bin
Summary: bin components for the kata-qemu-lite package.
Group: Binaries
Requires: kata-qemu-lite-data = %{version}-%{release}
Requires: kata-qemu-lite-libexec = %{version}-%{release}
Requires: kata-qemu-lite-license = %{version}-%{release}

%description bin
bin components for the kata-qemu-lite package.


%package data
Summary: data components for the kata-qemu-lite package.
Group: Data

%description data
data components for the kata-qemu-lite package.


%package libexec
Summary: libexec components for the kata-qemu-lite package.
Group: Default
Requires: kata-qemu-lite-license = %{version}-%{release}

%description libexec
libexec components for the kata-qemu-lite package.


%package license
Summary: license components for the kata-qemu-lite package.
Group: Default

%description license
license components for the kata-qemu-lite package.


%prep
%setup -q -n qemu-qemu-lite-2.11.0
cd %{_builddir}
tar xf %{_sourcedir}/22ead3e0bfdb87516656453336160e0a37b066bf.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/10739aa26051a5d49d88132604539d3ed085e72e.tar.gz
cd %{_builddir}/qemu-qemu-lite-2.11.0
mkdir -p capstone
cp -r %{_builddir}/capstone-22ead3e0bfdb87516656453336160e0a37b066bf/* %{_builddir}/qemu-qemu-lite-2.11.0/capstone
mkdir -p ui/keycodemapdb
cp -r %{_builddir}/keycodemapdb-10739aa26051a5d49d88132604539d3ed085e72e/* %{_builddir}/qemu-qemu-lite-2.11.0/ui/keycodemapdb
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600212009
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --disable-bluez \
--disable-brlapi \
--disable-docs \
--disable-curses \
--disable-gtk \
--disable-opengl \
--disable-sdl \
--disable-spice \
--disable-vte \
--disable-vnc \
--disable-vnc-jpeg \
--disable-vnc-png \
--disable-vnc-sasl \
--disable-fdt \
--disable-glusterfs \
--disable-libiscsi \
--disable-libnfs \
--disable-libssh2 \
--disable-bzip2 \
--disable-lzo \
--disable-snappy \
--disable-seccomp \
--disable-tpm \
--disable-slirp \
--disable-libusb \
--disable-usb-redir \
--disable-tcg \
--disable-debug-tcg \
--disable-qom-cast-debug \
--disable-tcg-interpreter \
--disable-tcmalloc \
--disable-curl \
--disable-rdma \
--disable-tools \
--disable-xen \
--disable-linux-aio \
--enable-kvm \
--enable-vhost-net \
--enable-virtfs \
--enable-attr \
--enable-cap-ng \
--target-list=x86_64-softmmu \
--extra-cflags="-O3 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -fPIE" \
--extra-ldflags="-pie -z noexecstack -z relro -z now" \
--libdir=/usr/lib64/kata-qemu-lite \
--libexecdir=/usr/libexec/kata-qemu-lite \
--datadir=/usr/share/kata-qemu-lite \
--python=/usr/bin/python2 \
--disable-werror
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1600212009
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kata-qemu-lite
cp %{_builddir}/capstone-22ead3e0bfdb87516656453336160e0a37b066bf/LICENSE.TXT %{buildroot}/usr/share/package-licenses/kata-qemu-lite/861af24907e399e873920dbbff1ea1dd73a9ba35
cp %{_builddir}/capstone-22ead3e0bfdb87516656453336160e0a37b066bf/LICENSE_LLVM.TXT %{buildroot}/usr/share/package-licenses/kata-qemu-lite/afc034c0ae47cbd47a99c6c5992d846511bb33ad
cp %{_builddir}/capstone-22ead3e0bfdb87516656453336160e0a37b066bf/bindings/python/LICENSE.TXT %{buildroot}/usr/share/package-licenses/kata-qemu-lite/861af24907e399e873920dbbff1ea1dd73a9ba35
cp %{_builddir}/keycodemapdb-10739aa26051a5d49d88132604539d3ed085e72e/LICENSE.BSD %{buildroot}/usr/share/package-licenses/kata-qemu-lite/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8
cp %{_builddir}/keycodemapdb-10739aa26051a5d49d88132604539d3ed085e72e/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/kata-qemu-lite/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/qemu-qemu-lite-2.11.0/COPYING %{buildroot}/usr/share/package-licenses/kata-qemu-lite/2b9d60c2972b476384af9900276837ac81954e80
cp %{_builddir}/qemu-qemu-lite-2.11.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/kata-qemu-lite/c5041828c23a816cc38e662b61032e959cb86893
cp %{_builddir}/qemu-qemu-lite-2.11.0/COPYING.PYTHON %{buildroot}/usr/share/package-licenses/kata-qemu-lite/4fb749718a2ccd73467eb2351b1acd621f44a353
cp %{_builddir}/qemu-qemu-lite-2.11.0/LICENSE %{buildroot}/usr/share/package-licenses/kata-qemu-lite/0af1677615a1f197b23b9a8c28f65ea80125d9a0
cp %{_builddir}/qemu-qemu-lite-2.11.0/disas/libvixl/LICENCE %{buildroot}/usr/share/package-licenses/kata-qemu-lite/25383eb1c76eae5993e92a1cf2b75d58e599bbf5
cp %{_builddir}/qemu-qemu-lite-2.11.0/linux-headers/COPYING %{buildroot}/usr/share/package-licenses/kata-qemu-lite/d3c00f9396c6d0277727cec522ff6ad1ea0bc2da
cp %{_builddir}/qemu-qemu-lite-2.11.0/slirp/COPYRIGHT %{buildroot}/usr/share/package-licenses/kata-qemu-lite/300155fc2f02d0dbcb70bd405fb4bc620c78eb73
cp %{_builddir}/qemu-qemu-lite-2.11.0/tests/qemu-iotests/COPYING %{buildroot}/usr/share/package-licenses/kata-qemu-lite/2b9d60c2972b476384af9900276837ac81954e80
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/share/kata-qemu-lite/qemu/u-boot.e500
## install_append content
# rename to avoid conflict with qemu package
for file in %{buildroot}/usr/bin/*
do
dir=$(dirname "$file")
bin=$(basename "$file")
new=$(echo "$bin"|sed -e 's/qemu-/kata-qemu-lite-/g' -e 's/ivshmem-/ivshmem-lite-/g' -e 's/virtfs-/kata-virtfs-lite-/g')
mv "$file" "$dir/$new"
done
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kata-qemu-lite-ga
/usr/bin/kata-qemu-lite-pr-helper
/usr/bin/kata-qemu-lite-system-x86_64
/usr/bin/kata-virtfs-lite-proxy-helper

%files data
%defattr(-,root,root,-)
/usr/share/kata-qemu-lite/qemu/QEMU,cgthree.bin
/usr/share/kata-qemu-lite/qemu/QEMU,tcx.bin
/usr/share/kata-qemu-lite/qemu/acpi-dsdt.aml
/usr/share/kata-qemu-lite/qemu/bamboo.dtb
/usr/share/kata-qemu-lite/qemu/bios-256k.bin
/usr/share/kata-qemu-lite/qemu/bios.bin
/usr/share/kata-qemu-lite/qemu/efi-e1000.rom
/usr/share/kata-qemu-lite/qemu/efi-e1000e.rom
/usr/share/kata-qemu-lite/qemu/efi-eepro100.rom
/usr/share/kata-qemu-lite/qemu/efi-ne2k_pci.rom
/usr/share/kata-qemu-lite/qemu/efi-pcnet.rom
/usr/share/kata-qemu-lite/qemu/efi-rtl8139.rom
/usr/share/kata-qemu-lite/qemu/efi-virtio.rom
/usr/share/kata-qemu-lite/qemu/efi-vmxnet3.rom
/usr/share/kata-qemu-lite/qemu/keymaps/ar
/usr/share/kata-qemu-lite/qemu/keymaps/bepo
/usr/share/kata-qemu-lite/qemu/keymaps/common
/usr/share/kata-qemu-lite/qemu/keymaps/cz
/usr/share/kata-qemu-lite/qemu/keymaps/da
/usr/share/kata-qemu-lite/qemu/keymaps/de
/usr/share/kata-qemu-lite/qemu/keymaps/de-ch
/usr/share/kata-qemu-lite/qemu/keymaps/en-gb
/usr/share/kata-qemu-lite/qemu/keymaps/en-us
/usr/share/kata-qemu-lite/qemu/keymaps/es
/usr/share/kata-qemu-lite/qemu/keymaps/et
/usr/share/kata-qemu-lite/qemu/keymaps/fi
/usr/share/kata-qemu-lite/qemu/keymaps/fo
/usr/share/kata-qemu-lite/qemu/keymaps/fr
/usr/share/kata-qemu-lite/qemu/keymaps/fr-be
/usr/share/kata-qemu-lite/qemu/keymaps/fr-ca
/usr/share/kata-qemu-lite/qemu/keymaps/fr-ch
/usr/share/kata-qemu-lite/qemu/keymaps/hr
/usr/share/kata-qemu-lite/qemu/keymaps/hu
/usr/share/kata-qemu-lite/qemu/keymaps/is
/usr/share/kata-qemu-lite/qemu/keymaps/it
/usr/share/kata-qemu-lite/qemu/keymaps/ja
/usr/share/kata-qemu-lite/qemu/keymaps/lt
/usr/share/kata-qemu-lite/qemu/keymaps/lv
/usr/share/kata-qemu-lite/qemu/keymaps/mk
/usr/share/kata-qemu-lite/qemu/keymaps/modifiers
/usr/share/kata-qemu-lite/qemu/keymaps/nl
/usr/share/kata-qemu-lite/qemu/keymaps/nl-be
/usr/share/kata-qemu-lite/qemu/keymaps/no
/usr/share/kata-qemu-lite/qemu/keymaps/pl
/usr/share/kata-qemu-lite/qemu/keymaps/pt
/usr/share/kata-qemu-lite/qemu/keymaps/pt-br
/usr/share/kata-qemu-lite/qemu/keymaps/ru
/usr/share/kata-qemu-lite/qemu/keymaps/sl
/usr/share/kata-qemu-lite/qemu/keymaps/sv
/usr/share/kata-qemu-lite/qemu/keymaps/th
/usr/share/kata-qemu-lite/qemu/keymaps/tr
/usr/share/kata-qemu-lite/qemu/kvmvapic.bin
/usr/share/kata-qemu-lite/qemu/linuxboot.bin
/usr/share/kata-qemu-lite/qemu/linuxboot_dma.bin
/usr/share/kata-qemu-lite/qemu/multiboot.bin
/usr/share/kata-qemu-lite/qemu/openbios-ppc
/usr/share/kata-qemu-lite/qemu/openbios-sparc32
/usr/share/kata-qemu-lite/qemu/openbios-sparc64
/usr/share/kata-qemu-lite/qemu/palcode-clipper
/usr/share/kata-qemu-lite/qemu/petalogix-ml605.dtb
/usr/share/kata-qemu-lite/qemu/petalogix-s3adsp1800.dtb
/usr/share/kata-qemu-lite/qemu/ppc_rom.bin
/usr/share/kata-qemu-lite/qemu/pxe-e1000.rom
/usr/share/kata-qemu-lite/qemu/pxe-eepro100.rom
/usr/share/kata-qemu-lite/qemu/pxe-ne2k_pci.rom
/usr/share/kata-qemu-lite/qemu/pxe-pcnet.rom
/usr/share/kata-qemu-lite/qemu/pxe-rtl8139.rom
/usr/share/kata-qemu-lite/qemu/pxe-virtio.rom
/usr/share/kata-qemu-lite/qemu/qemu-icon.bmp
/usr/share/kata-qemu-lite/qemu/qemu_logo_no_text.svg
/usr/share/kata-qemu-lite/qemu/qemu_vga.ndrv
/usr/share/kata-qemu-lite/qemu/s390-ccw.img
/usr/share/kata-qemu-lite/qemu/s390-netboot.img
/usr/share/kata-qemu-lite/qemu/sgabios.bin
/usr/share/kata-qemu-lite/qemu/skiboot.lid
/usr/share/kata-qemu-lite/qemu/slof.bin
/usr/share/kata-qemu-lite/qemu/spapr-rtas.bin
/usr/share/kata-qemu-lite/qemu/trace-events-all
/usr/share/kata-qemu-lite/qemu/vgabios-cirrus.bin
/usr/share/kata-qemu-lite/qemu/vgabios-qxl.bin
/usr/share/kata-qemu-lite/qemu/vgabios-stdvga.bin
/usr/share/kata-qemu-lite/qemu/vgabios-virtio.bin
/usr/share/kata-qemu-lite/qemu/vgabios-vmware.bin
/usr/share/kata-qemu-lite/qemu/vgabios.bin

%files libexec
%defattr(-,root,root,-)
/usr/libexec/kata-qemu-lite/qemu-bridge-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kata-qemu-lite/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/kata-qemu-lite/0af1677615a1f197b23b9a8c28f65ea80125d9a0
/usr/share/package-licenses/kata-qemu-lite/25383eb1c76eae5993e92a1cf2b75d58e599bbf5
/usr/share/package-licenses/kata-qemu-lite/2b9d60c2972b476384af9900276837ac81954e80
/usr/share/package-licenses/kata-qemu-lite/300155fc2f02d0dbcb70bd405fb4bc620c78eb73
/usr/share/package-licenses/kata-qemu-lite/4fb749718a2ccd73467eb2351b1acd621f44a353
/usr/share/package-licenses/kata-qemu-lite/861af24907e399e873920dbbff1ea1dd73a9ba35
/usr/share/package-licenses/kata-qemu-lite/afc034c0ae47cbd47a99c6c5992d846511bb33ad
/usr/share/package-licenses/kata-qemu-lite/c5041828c23a816cc38e662b61032e959cb86893
/usr/share/package-licenses/kata-qemu-lite/d3c00f9396c6d0277727cec522ff6ad1ea0bc2da
/usr/share/package-licenses/kata-qemu-lite/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8
